<?php

session_start();
include_once('../class/mypdo.class.php');
$data=array();

$data['success']=false;
$tab=array();
$data['vhu_Bdd']=array();
$data['fichier_Excel']=array();
$data['result']=array();
$data['live']=array();
$mypdo=new mypdo();



require_once '../class/PHPExcel/IOFactory.php';
	$file1='../uploads/Extraction _2712_Base ICPE MEEM.xlsx';
    $file2='../uploads/VHU_Syderep.xlsx';



$BStyle = array(
			'borders' => array(
					'allborders' => array(
							'style' => PHPExcel_Style_Border::BORDER_THIN
					)
			)
	);




$objPHPExcel = PHPExcel_IOFactory::load($file1);//On charge le fichier ICPE
$VHU_Syderep= PHPExcel_IOFactory::load($file2);//On charge le fichier VHU_Syderep

$sheet = $objPHPExcel->getSheet(0);//On veut la feuille 1
$sheet_VHU_Syderep= $VHU_Syderep->getSheet(0);//On veut la feuille 1
$i=2;
	$columnA = 'A';
	$columnB='B';
	$columnC='C';
	$columnD='D';
	$columnE='E';
	$columnF='F';
	$columnG='G';
	$columnH='H';
	$columnI='I';
	$columnJ='J';
	
	$lastRow = $sheet->getHighestDataRow();
	
/**
 * [$row description]
 * @var integer
 */
		for ($row = 2; $row <= $lastRow; $row++) {


                   if($sheet->getCell($columnA.$row)->getValue()!=null){

	 			array_push($data['fichier_Excel'],$sheet->getCell($columnA.$row)->getValue()


	 					);//Permet de voir ce qu'on récupère dans un tableau

	 			



	 			/*$requete=$mypdo->Centres_VHU_Actifs($sheet->getCell($columnB.$row)->getValue());*/




$data['success']=true;


	 		}


		}





/*

 	$vhu=array();
 	array_push($vhu,'1000 PIECES AUTOS','2M','2 RM','4AS Pièces AUTO','A LA CASSE AUTO JJ','A l\'EMPORTE PIECES','AB AUTO PIECES',
'AALYAH RECYCLAGE','ABC NEGOCE','abrafer','ABS AUTO PIECES','THIEBAUD-ACCI AUTO','ACCIAUTO','ACCIMOTO','ACR34',
'ACTIVE AUTO - CARCASSONNE','ACYCLEA','AD - ARNAUD DEMOLITION','AUTO DEPOLLUTION ORDAN','AFM RECYCLAGE - CARCASSONNE','SOCIETE D\'EXPLOITATION AGDE AUTO PIECES',
'AGOGUE','AGV 95','ALBERDI','S2A','ALLO AUTO SERVICE','ALLO CARS CASSE','ALLO CASSE AUTO-ATHIS MONS','ALPA ACIERIES LAMINOIRS DE PARIS'
,'ALPES RECUPERATIONS','ALTVILLIER','Amf','ANG AUTO DEMOLITION','ANJOU CASS','ANNONAY SERVICE AUTO','AUTO PIECES - CHANAS'
,'ARC EN CIEL RECUPERATION','ARCA CHUDEAU','ARDEN PIECES AUTO','ARGONAY PIECES AUTO','ARNAUD GODDET','ARTASO','ETS ARTMANN - DOUBS RECYCLAGE'
,'ETS ASCONE JOSEPH','AUTO SERVICE DISTRIBUTION','FRANCHETEAU RECYCALGE','AFM RECYCLAGE - AVRILLE','ATP','AUBORD AUTO PIECES'
,'AUDE AUTO PIECES','AUTO 2001 - GONESSE','AUTO CASSE 2000 - DIRAC','AUTO - CASSE LECOMPTE DANIEL','AUTOCASSE PONTIVY','CGCA AUTOCHOC'
,'A.D.F','AUTO DEMOLITION PICARDE','AUTO DEMOLITION VITREENNE','AUTO DESTRUCTION ALAIN','CASSE AUTO DESTRUCTION','AUTO FLORANGE'
,'AUTO OPREMA','AUTO PIECES GIBAND PEYRACHE','AUTO PIECE SERVICE','AUTO PIECES 58 - COSNE SUR LOIRE',
'AUTO PIECES 82 - MONTBARTIER','AUTO PIECES 84+ - CARPENTRAS','AUTO PIECES LOUHANS - BRANGES','JEAN BERNARD','AUTO - PIECES RAVEL'
,'AUTO PIECES DU POUZIN','AUTO PIECES-SENS','AUTO PIECES TROYENNES','AUTO PIECES VOIRONNAISES','AUTORECUP2081'
,'AUTO RECUPDOULE','AUTO RECUPERATION BIRIEN','AUTO RECYCLAGE','AUTO SERVICE DENIZ LONS','AUTO STOCK PIECES - DENAIN','AUTODIS'
,'A.I.R.','AUTO PIECES 71 - GILLY SUR LOIRE','AUTOS PIECES DU FORT','AUTO THIONVILLE','AUTUSSE ET FILS','AVENIR AUTOMOBILE'
,'Avenir Recyclage ouest','AVENYR','AXE AUTO','AXIOMAUTO','AUTO PIECES SIMON','AZUR AUTO','BALDO RECUPERATION','GARAGE BALLERDIER'
,'BARSSE CLAUDE','BARTIN RECYCLING SOBOREC - BEGLES','BAUDON CHABOSY RÉCUPÉRATION','BAUDON ROUVREAU RECYCLAGE','BDS RECYCLAGE'
,'BEAUNE.AUTO PIECES','BECK EXPORT AUTOMOBILE','SN BEHEM','BELLES AUTO DEPANNAGE','BELLESOEUR AUTOMOBILES','BENOIST AUTO PIECES'
,'BERTO','B.F.M. RECUPERATION','SUD OUEST AUTOS','DEMOLITION AUTOMOBILE','BOCHATAY MISSILIER','BONNIN CARECO','BORNOT ET SERRE'
,'BOUDOU RECUPERATION','BOUDOUSSIER FRERES','DEMOLITION AUTOMOBILE GARAGE BOURGET HAMEL','BOURGOGNE RECYCLAGE'
,'BRAND PASCAL PIECES AUTO OCCASIONS'
,'BRESSE RECUP\'','BRESSUIRE RECUP AUTO','CASSE AUTO BRETON','BRIANE ENVIRONNEMENT','BROCELIANDE PIECES AUTO','ETABLISSEMENTS GEORGES BRUHAT'
,'BRUNO OTO PIECES','CARCASSE DEPANNAGE','ETABLISSEMENTS GILLES CARCY','CARMOTEX','CARROSSERIE AURAN','CARS PIECES EXPRESS'
,'CARZAT MATERIELS','CASSE AUTO LAVIT PATRICK','CASSE AUTO 2000 - SAULNOT','CASS\'AUTO MEUNIER C','CASSE 03','CASSE AUTO DE VAVRAY'
,'CASSE AUTO 05 - LA BATIE NEUVE','CASSE AUTO 28','CASSE AUTO','CASSE AUTO D\'ARMOR','CASSE AUTO DU VERON','CASSE AUTO JACKY'
,'CASSE AUTO LA MONBEQUINOISE','CASSE AUTO SERVICES','CASSE AUTOS TCHIJAKOFF','CASSE AUTO PIECES - ESMANS','AUTO CASSE AUXONNAISE'
,'CASSE DE LA SOURCE','CASSE DU VAL D\'ARNOUX','LA CASSE','CASSE NORMANDIE','OCCA PIECES','CASSE RN 74','CASTAGNIER - PERRET'
,'CASTEL AUTO DESTRUCTION','AUTO CASSE','CAZI','ROGIER SEBAG','CDA COTE BASQUE','CDMA','CDRA - CENTRE DE DEPOLLUTION ET DE RECUPERATION AUTOMOBILE'
,'CELLIER DEPANNAGE','CENDRES','CENTRA CASSE','CENTRALE CASS\'AUTO','CENTRE AUTO DU PAYS DE CRUSSOL','CENTRE AUTO SERVICE'
,'CENTRE DE RECUPERATION DU LIBOURNAIS','CENTRE RECYCLAGE AUTO 73','ESKA-BEAUTOR','SFM INDUSTRIE','C. M. R. RECYCLAGE'
,'CHANFRAU ENVIRONNEMENT','CHATIN ALAIN','CHATREIX','CHOC 03','CHOLET RECUP','CHRISTIAN RECUPER','CHRISTOM RECUPERATION'
,'CIMETIERE AUTO','COLIGNY','COMMINGES METAUX SERVICES','COMPTOIR DU REEMPLOI','COPA','CORDEBAR','CORREZE RECUPERATION'
,'CORSE RECUPERATION FERRAILLE','COUTRA CASSE AUTO','CRA AUTOMOBILE LE PONTET','D.G RECYCLAGE GUELLA DAVID','DEMOLITION AUTO LOREAU PATRICK'
,'DABEC','DEPOLLUTION AUTOMOBILE CHELLOISE','DADDI SRI','DAINVILLE RECYCLAGE','DALMASSO JEAN PAUL','DALUZ MARIO','DB AUTO ASSOCIES'
,'DB AUTO','DEBRITO','DECONS-LE PIAN MEDOC','DECONS - AUCAVILLE','DECONS - ST ASTIER','DECONS - ECHILLAIS','DEJOUX','DEL AUTO PIECES'
,'DEL FRANCIS','DELPIECES AUTO','ENTREPRISE DELABRE NOEL','AUTO CASSE DELAGE MICHEL','DECLOS ET FILS','DELILE ET FILS - AUCH'
,'DEMOLITION AUTOMOBILE DELLA CASA','DEMOL\'ROCHOISE','DEMOLIAUTO','DEMOLITION AUTO CALARD','ASVISIO RAYMOND','DEMOLITION LUCONNAISE DE VEHICULES'
,'MARIE - CLAUDE MONNIER','DEMOLITION SAINT GENOISE','DEM\'S AUTOS FRANCE','DEM\'S AUTO CHARTRES','AUTO STOCK PIECES - DENAIN','DEPANNAGE 70'
,'GUY DAUPHIN ENVIRONNEMENT - LA ROCHE SUR YON','DEPANNAGE PH VERDIER','DESOS\'CAR VHU','DISCOUNT AUTOMARCHE','DISTRIFIER','Stéphane DORIZON'
,'DRD AUTO PIECES','DRM02','DURANCE DEPANNAGE AUTO MOTO','DEMOLITION AUTOMOBILE DUROULE','DYNATECH INDUSTRIES','ECO CASSE','EDECIMO RECUPERATION'
,'EIRL moy tanguy','ENVIRONNEMENT SERVICES','EPAVES SERVICE 77','EPUR CANTRE - MACON','EPUR CENTRE - CUSSET','EPUR CENTRE - DIGOIN'
,'EPUR CENTRE - ARNAS','ESKA - ST DIZIER','ESKA - THIONVILLE','ESKA - NOUZONVILLE','ETABLISSEMENTS GABILLAT FRERES','SOCIETE D\'EXPLOITATION ETABLISSEMENTS LE FLOHIC'
,'MARTINEAU LOUIS','SUD OUEST AUTOS','ETS FAURE','ETS JOSEPH MICHEL','ABC DEMOLITION AUTO','CASSE AUTO ROLLAND','LE NETTOYEUR','LONGUEVILLE AUTOS'
,'EUROP CASSE','EUROPIECES AUTO','EVN','EXP JM AUTOS','EYMERY RECUPERATION','FAUCIGNY AUTO - PIECES','FAURIE JEAN-MARIE','FCDA','FER HARRY'
,'J.FERRIOL METAUX','FERS - LES HERBIERS','FERS ET METAUX - VERDUN','FERT DEMOLITION HERAULT','FERT DEMOLITION - VALREAS','FERT DEMOLITION - ETOILE SUR RHONE'
,'FL AUTO','FL INDUSTRIE - VALREAS','FLASH AUTO - GRAULHET','RECYCLAGE FMC','FOLLIN RECUP\'AUTO','FONGARO RECYCLING','FORTIN AUTOMOBILE','FAS DEMOLITION'
,'FOURMENT ET FILS','ETS FOURNETON LOUIS','FREY JEAN JACQUES','FUSSY PIECES AUTOS','ROMI BRETAGNE - ST MALO','GALLO FRANCE - ANICHE'
,'GALLO LITTORAL - DUNKERQUE','DAVID ALEXANDRE','GARAGE BOURDAIS','OR\'KAZ JMB','GARAGE DES OLIVIERS','GARAGE DU FOURNEAU','GARAGE DU MANOIR'
,'GARAGE HERICOURTOIS','GARAGE LEADER','GARDET ET DE BEZENAC ENVIRONNEMENT','GATTE RAPHAEL','GAULTIER','GUY DAUPHIN ENVIRONNEMENT','GUY DAUPHIN ENVIRONNEMENT FOUGERES'
,'GUY DAUPHIN ENVIRONNEMENT - GUIPAVAS','GUY DAUPHIN ENVIRONNEMENT BUIRE','GENERALL AUTOS - ST LOUIS','GIA CASS\'2000','GIEVRES AUTO','GLOS AUTOMOBILES'
,'GOCYK KUZMIR FILS','ROGER GOUVERNAYRE ET FILS','GOYENECHE JEROME DEMOLISSEUR','SDMM - AUTO CASS 83','GUY DAUPHIN ENVIRONNEMENT - HENNEBONT'
,'GUY DAUPHIN ENIVRONNEMENT LA COURNEUVE','QUINSON - FONLUP','GT AUTO RECYCLAGE DE VOITURE','GTI GROUPE','GUAINVILLE RECUPER'
,'GUELLE FRERES','GUY DAUPHIN ENVIRONNEMENT - GENNEVILLIERS','AUTO-PIECES GUY VOISIN','ENTREPRISE GUYONNET','GOYOT ENVIRONNEMENT - KERUIGNAC'
,'LUDOVIC LE GAL - PLOUFRAGAN','HARDY MAURICE','PAUL HARDY','HASLOIN','HAUTE CANCE AUTO FER','CASSE','CASSE AUTO HECHT HENRI FILS','HENAULT'
,'HOUDELOT NEGOCE','HYPER AUTO','INDRA - JARDIN AUTO PIECES','INDRA - RESOURCE AUTO PIECES','J3A AUTO','JACKY RECUPERATION AUTOS'
,'JACQUET ET FILS','JAMOT','JAQU\'AUTO','JCM DEPANNAGE AUTO','JEANNOT SUPERCASS','JESTIN AUTOS','JIMMY AUUTO','JOANNIN','JOUVE RECYCLAGE'
,'ETABLISSEMENTS JULIEN','LA PIECE AUTOMOBILE','LA P\'TITE CASSE','GARAGE LALOUETTE','DEPANAUTO AURAY','LAND AUTO','LAPOULE ROLAND','L\'AUTOSATISFACTION'
,'LE BRIS GARAGE POIDS LOURDS','LE FEUVRIER','LUDOVIC LE GALL - PLOUFRAGAN','LUDOVIC LE GALL - PLOUMILLIAU','CASSE AUTO DE BELLEVUE','RECUP\'29'
,'LELIEVRE RECYCLAGE','LEREAU DAVID','LESEVE TDRA','LION AUTO CASSE','LOIRET RECYCLAGE','LPVO','LUDOVIC LE GALL - LE SOURIN','LVA','BAPTISTE WALTER'
,'BERGER GEORGES - LOUIS','MAG\'AUTO','M.P.A.','MAGREN','MAINE RECUPER','MARCEL DURET','MARCHETTO RECYCLAGE - ESMANS','MARX SPAENLIN SOMETALOR'
,'MAYEUR FRERES','MAZIERES','MB AUTO','ETS MECANAUTO','MELI JEAN - ST ETIENNE','MELI PIECES AUTO'
,'ETABLISSEMENTS J MENUT_86 - MIGNE AUXANCES'
,'MERU AUTO PIECES','GUY DAUPHIN ENVIRONNEMENT - ILLZACH','MG AUTO CASSE','MIGNOT AUTO PIECE','GUY DAUPHIN ENVIRONNEMENT - CHEMINOT'
,'ML PIECES AUTO','M.O - STOP AUTOS','MODUL\'AUTO','MONDIALE PIECES AUTO','SAGOT JACQUES','MOOKY AUTO','MOREAU C.','DEMOLITION AUTOS MOREL JACKY'
,'RECUPERATION FERS ET METAUX - CHASTEL','MULTI CHOC','MULTI SERVICES AUTO (MSA)','MULTIMETAL','MUNOZ','MB RECYCLAGE','MYTNIK SAAF'
,'N7AUTO PIECES','NEGOCE AUTO - CHOLET','NEGOMETAL','NICOLAY FILS','O.P.A.L','ORLEANS SUD AUTO - CERCOTTES','ORNAUTO','TEN CAR'
,'PASCALON FRERES','PASSENAUD RECYCLAGE - COURBEPINE','PASSENAUD HA METAL','PASSENAUD RECYCLAGE - CHAMPAGNE','FERT DEMOLITION - ETOILE SUR RHONE'
,'ETABLISSEMENTS POIRIER','PORTIGLIATI','PRAXYCENTRE - CUSSET','ETABLLISEMENT PRIEUR','PROFER','PROLIFER RECYCLING-ST PHILBERT'
,'PEREZ FILS','PHENIX RECYCLAGE','POS BAZIN MICHEL','PICHEREAU PHILIPPE','PIEC\'AUTO','PIEC\'AUTO26','PIECES AUTO 47','PIECES AUTO 71'
,'PIECES AUTO DULIN','PIECES AUTO GAP','PIECES AUTO LAURENT','PURFER - CARROS','MAIARELLI','PURFER','CASSE FALLONE','RATTIER'
,'ORLEANS SUD AUTO - CERCOTTES','RECUP 16','RECUPAUTO - ANJOU','RECUP AUTO MERCIER','RECUP AUTOS 24 - MONTREM',
'PURFER - OLLIOULES','RECUPERAUTO','RECUP 44','ETS MAYOUX','RECUP AUTO GRENIER - CREUZIER','RECUP AUTO GROBEN','RECUP','AUTO MONESTIER','ETS BERNARD','RECUPERATION SERVICES AUTO ROCHIS'
,'RECYCLAGE AUTO PIECES','LES RECYCLEURS BRETONS','GUY DAUPHIN ENVIRONNEMENT - VERDUN','ETS KALIAKOUDAS','REMORQUAGE 42 MONTBRISON PIECES AUTO'
,'ETABLISSEMENTS GEORGES REMY','REVIVAL - CHELLES','REVIVAL (ex STRAP) - SAINT SAULVE','REVIVAL - LE GRAND QUEVILLY','RIBEIRO ET ASSOCIES'
,'BARTIN RECYCLING - COSNE COURS SUR LOIRE','RN3 AUTOS','ROHR ENVIRONNEMENT','ROMI BRETAGNE - ST MALO','ROMI BRETAGNE - LANNION','ROMI BRETAGNE - QUIMPER'
,'ROMO PIECES AUTO','ROSNY AUTO PIECES','ROSSI','ROUGHOL','ROUX RECUPERATION','ROYER','PHILIPPE RUBIO - LONS','AUTO - CHOC','RVA','ENTZ'
,'SARL MONNOYEUR RECYCLAGE DEMOLITION','SACASS AUTO','SAICA NATUR SUD','SAINT MARCEL AUTO PIECES','NG 52 RECUP','SAPAU','AUTOS SERVICES SEPTEMES'
,'ACA - NIEPPE','ETS D\'ANTONELLI','ATOUT FER','AUTO CASSE - GIGNAC','AUTO CASSE MARANA - BORGO','SN AUTO PIECES59','BAKEH','ETS BELLE ET FILS'
,'BANCONE','BRDM','CASS AUTO VG','CASSE AUTO-NILVANGE','CODIPIECE','DEMANTELLEMENT RECUPERATION INDUSTRIEL','BEUREL DEMOLITION AUTO'
,'DEMAX','CORSE RECUPERATION FERRAILLE','TESSIER','ETS BIEYSSE PERE ET FILS','ETABLISSEMENTS TILLET RECUPERATION','FRANCAIS FRERES','GIZZI DEMOLITION'
,'LAPOULE STEPHANE','M3CN','MASSET','MECA PRO','MIELLE RECUPERATION','MVU','PASSENAUD HENRI RECUPERATION','PRETEMER AUTO','SCOTTO'
,'ARMABESSAIRE','ATOUT - FER RECUPERATION','AUBORD RECYCLAGE','AXIA','SAS ETS DUVAL','FL INDUSTRIE - LA COUCOURDE','GARAGE BAUDOIN'
,'INDRA - A7 AUTO PIÈCES','MVI','SURPLUS AUTO 81 - GAILLAC','SURPLUS MOTOS','PIECES D\'OCC','SAVRA','SB AUTO PIECES','SCAFA 93'
,'SAS SCHIED ENVIRONNEMENT RECYCLAGE','Ets Alain SCHMIDT','SCRATCH AUTO','SEA','SEPCHAT','C.SERRAND','SIBCAR','SIRMET - BRIVE LA GAILLARDE'
,'SIRMET - BOULAZAC','SMAC','SNBL','SOCIETE NANTAISE DE RECYCLAGE AUTOMOBILE','SOCIETE NOUVELLE GARAGE PIECES AUTO','SDRA','SOCIETE NOUVELLE DEPRE AUTOMOBILES'
,'SN FORNES','SOLUVAL','SORAR','SOSAREC','SPLM COUDOURET','SPOA','SRVV VACHER','STEPHAN','STOCK CASSE 70','SUD OUEST AUTOMOBILES','ETS MAYOUX'
,'L\'AUTOSATISFACTION','SHAMROCK ENVIRONNEMENT - AUXERRE','SURPLUS AUTOS - VITROLLES','SURPLUS MARSEILLE','TAHAR PIECES AUTO D\'OCCASION'
,'TERROTIN','TILT AUTO - DURDAT LAREQUILLE','TILT AUTO 56 - CLEGUER','ETS TIOZZO','ETS TOUZERY','TRANSMETAL','MAURICE TROTIGNON'
,'V2M','VACHEZ INSDUSTRIE','JPC GARAGE VASSEUR','CASSE AUTO DESTRUCTION','ETS VERGER','VIDAL CASSE AUTO','VIERI SERGE','VIGNIER F'
,'VIGOT','VILLEFRANCHE AUTO SERVICES','DECONSTRUCTION AUTOS VILLETON','AUTO - DEMOLITION - CHINNARD','VOG','WALDECK AUTO PLUS'
,'ETS WAUCQUIER FRERES','WDA','WITTMANNA','XIXONET','YORUK AUTO','METALFER','ZIGLER GUERSAN','ZITOUNTERK CASSE','AUTO TILT - CERCOTTES'
,'KINTZ FRERES','KIT CASSE AUTO-YILMAZ','KOLENO ET FILS','LA PIECE','LA PIECE AUTOMOBILE','DSA','VERI CASSE','DEMOLITION AUTOS MARTY','RECUP\'AUTO','ANVA','METAL FER RECYCLAGE','METAL FER RECYCLAGE','BEAUFILS RECUPERATION','ESKA - LANGRES','HUGONENC NEGOCE','EUROPIECES','METAUX FERS VALORYS','MARIE DIDIER AUTOMOBILES','METAL REUNION','VOSGES OCCAS','ACCUEIL AUTO PIECES','VARENNES PIECES AUTOS','PIECES AUTO FIFI TURIN','KIT AUTO','PRAXY CENTRE','BRION','AUTO PIECE BURGUIERE'
,'CUB AC CASSE','WOIPPY CASSE','DAC GRELLIER','THB','STOCK AUTO','RECUPERATION DE MACEDO','STOCK CAR','AUTO EXPRESS',
'JIMMY AUTO','AUTO BC SERVICES','CASSECO 78','SOCIETE NOUVELLE STOCK CASS','GENEVE OCCASION','AYROLES COURAIS',
'CAZENAVE PIECES AUTO','CAR INTER','BREIZ REMORQUAGE','RECUPERATION AUTOMOBILE MALEWICZ','NADAL','SPDO'
,'DONNEVILLE CASSE AUTO','ESCALE AUTO','CASSE AUTO CHEVALIER','AUTODICO','ARTISANS REUNIS 34'
,'HENON FRERES','DECONSTRA','BUCHOUL RECYCLAGE','ATLANTIC METAL','FIEVEZ AUTOMOBILES'
,'AD AUTOMOBILE','SEPCHAT 28','HERVE RECUPERATION','TRIGENIUM','CARLUS CASS','CASSE AUTO FOUGERAISE','FERROLAC','BARBAT RECYCLAGE','THEBAULT AUTO PIECES','SEVP AUTO CLERMONT','SOS PIECES AUTO','CHAGNY AUTO CASSE'
,'DEMOLITION DU TILLEUL','MEDITERRANEE AUTO PIECES','AUTO MOTO CENTER','NAZA AUTO','ADOUR METAL','ARPO','CALARD FRERES','INDUSPA','BOISSEAU PIECES AUTO','CASSE AUTO AUBYGEOISE','LEJEUNE AUTOMOBILE','CASSE DU VAL D\'ARROUX','ALOUETTE AUTO PIECES','DUQUENET Julien','CASSE AUTO BAYARD','BREIZ AUTO','OUEST CASS','EXCOFFIER FRERES'
,'CASSE AUTO DU PETIT RESTO','BIG BENNES','VACHEZ INDUSTRIE','AD AUTOMOBILE','ROCADE AUTO PIECES','STAND 90','AUTO CASSE SERVICE','AUTO CASSE CHANEL','EURO AUTOMOBILES','DUPUIS AUTO PIECES','SEVA','GARAGE BON PORT','FAURE FILS CTMO','DEMOLITION AUTO HEURTER','EURE METAL','PASCAULT','CERNAY ENVIRONNEMENT','TOPICO AUTO'
,'CERNAY ENVIRONNEMENT','HASLOUIN','CAP AUTO','AUTO DISCOUNT 54','TABARD AUTOS DEMOLITION'
,'PIECES AUTOS MOTOS OCCASIONS','CASTEL AUTO DECONSTRUCTION','AUTO 4','CAPNOR','PRO\'PIECES','AUTOCCASION','VENDEE RECUPERATION','BONN\'AUTO PIECES','BULLITT AUTO','RECUP\'AUTO MONESTIER','AUT\'OCCAS'
,'AUTO 61','DUPAS','AUTO PIECES 14','TOURNUS DEMOLITION AUTO','CASSE DIDEROT','RENAULT FLINS','AUTO TRIO +','GOSSELIN DURIEZ','DEPANN\'AUTO','SDP AUTO','ADOUR PIECES AUTOMOBILES','N7 AUTO PIECES','RECUPFER'
,'CASSE 2000','LAMBERT','SOPPE VEHICULES INDUSTRIELS','RTG','PRESTA\'CASSE',
'DUBOIS KASS AUTO','CHAMPIER AUTO PIECES','SOREMAINE VL','ARGONAY PIECES AUTOS'
,'ARGONAY PIECES AUTOS','STOP PIECES AUTO','DRNS','ED PIECES AUTO','PLASTIFER'
,'EURAUTOS','AUTODROME 91','PERRIN FERS ET METAUX','CARAMBOLAGE 59','NEGOCE AUTO DU ROUMOIS','NEGOCE AUTO DU ROUMOIS','CAMBOUIS AUTO','GREZ PIECES AUTO','MG AUTOMOBILES','ROUEN AUTOMOBILES SERVICES'
,'BENOIT RINO','GUIDEL CASSE','MAIZIERES AUTOMOBILES','AMERICAFER','DEMANET DANIEL','PELISSIER','BRIONNAIS AUTO PIECES','CAMBOUI RECYCL\'AUTO','TRANS HIP AUTO','BCDE','RODRIGUES RECUPERATION RECYCLAGE'
,'PINET','JOC AUTO','HOURQUET ET FILS','BERAL AUTO','SOREVAC','ARTOIS METAUX'
,'LE BRIS OCCASIONS POIDS LOURDS','CLERMONT DEMOLITION AUTO','GACHON RECUPERATION BEAUJOLAISE','AUTOS DISCOUNT 61','LOSTIS RECYCLAGE','AUTOMECAPIECES','SOCIETE NOUVELLE FORNES','MILLAU PIECES AUTO RECYCLAGE'
,'CASSE 2000','LAMBERT','RACHETE FOURNI NEGOCE','AQUITAINE MOTO CASSE','RM OCCAS'
,'DEPANNAGE 25','DEPOL\'OISE','CENTRAL CASSE','A LA BONNE OCCAS','ALLMETAL','AUTO PIECES PIENNES'
,'CASSAUTO COYECQUES','FLEURY PIECES AUTO','MONDIAL AUTO','SPRA','AUTO RECYCLAGE DES VOSGES'
,'ABCR','GARE OCCASION 88','MASSACRIER','SIRMET SAS','CENTRE RECYCLAGE AUTO','EST METAL','REVIVAL'
,'BILLAUD PIECES & AUTOS','RECYCLE AUTO PIECES','NEVERS PIECES D\'OCCASION','ONZE RECYCLE','AUTO CASSE PLUS','BUTIN TERRIER','BOCHATAY MISSILLIER','59 RECUP','CAEN AUTO NEGOCE CAN','CHEVILLY AUTOS SPORT','GDE K\'AS','HAUDROY AUTO PIECES','CASSE AUTO DU LANGUEDOC','SAZEC');

*/

$requete=$mypdo->Centres_VHU_Actifs();

while ($r = $requete->fetch()) {
	//On récupère les centres vhu du fichier ICPE qui n'existent pas dans la BDD
	array_push($data['live'], $r[0]);
	
}
	 	
$i=2;
$row=2;
	 	foreach ($data['live'] as $value) {
for ($row = 2; $row <= $lastRow; $row++) {

if($value==$sheet->getCell($columnA.$row)->getValue())

            array_push($data['vhu_Bdd'],$value);
}

	 			 	}
	 			


	 			//Il faut faire une requête qui permette de récupérer tous les centres vhu enregistré avec leurs infos

/*
$requete=$mypdo->Centres_VHU_Actifs($data['live']);
$i=2;
$row=2;
while ($r = $requete->fetch()) {

	//On récupère les centres VHU du fichier ICPE qui existent dans la BDD pour les mettres dans un nouveau fichier Excel
		$sheet_VHU_Syderep->getCell($columnA.$i)->setValue($r[2]);
	 				
	 	$sheet_VHU_Syderep->getCell($columnB.$i)->setValue();
	 	
	 	$sheet_VHU_Syderep->getCell($columnC.$i)->setValue();
	 	
	 	$sheet_VHU_Syderep->getCell($columnD.$i)->setValue();

	 	$sheet_VHU_Syderep->getCell($columnE.$i)->setValue();

        $VHU_Syderep->getActiveSheet()->getStyle($columnA.$i)->applyFromArray($BStyle);



	 				$VHU_Syderep->getActiveSheet()->getStyle($columnA.$i)->applyFromArray(
	 						array('fill'=>
	 									
	 								array('type' => PHPExcel_Style_Fill::FILL_SOLID, 'color' =>
	 										array('rgb' => '92D050') )
	 						)
	 						);

	 				$i++;
}

		
*/
	 			



			//On crée un objet Excel pour écrire dans le fichier
		

$objWriter = new PHPExcel_Writer_Excel2007($VHU_Syderep);

	
		$objWriter->save('../uploads/VHU_Syderep_copie.xlsx');



echo json_encode($data);

	

/*************************************************************************************************/
	


